#!/usr/bin/env bash
# ****************************************************
#
#   Cask
#
# ****************************************************

brew tap caskroom/cask
brew tap caskroom/versions

applications=(
  1password
  aerial
  adobe-creative-cloud
  alfred
  appcleaner
  backblaze
  bartender
  basecamp
  bettertouchtool
  cleanmymac
  dash
  dropbox
  firefox
  flux
  google-chrome
  hazel
  imageoptim
  istat-menu
  iterm2
  keyboard-maestro
  moom
  notion
  nucleo
  omnigraffle
  rescuetime
  rocket
  sip
  sketch
  spotify
  transmit
  visual-studio-code
  quitter
  zoomus
)

for application in ${applications[@]}; do
  brew cask install $application 2> /dev/null
done

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# arq
# atom
# atom-beta
# balsamiq-mockups
# bitbar
# cheatsheet
# docker
# drobo-dashboard
# duet
# focus
# fontbase
# github-desktop
# gitscout
# google-drive
# hyper
# iconjar
# instacast
# kap
# keepingyouawake
# liteicon
# macvim
# mamp
# michaelvillar-timer>
# mongodb-compass
# noun-project
# paw
# postgres
# rocket
# screenflow
# screenhero
# shortcat
# skyfonts
# sublime-text
# superduper
# toggldesktop
# tower2
# twitch
# visual-studio-code-insiders
# vlc
