#!/usr/bin/env bash
# ****************************************************
#
#   ESLint
#
# ****************************************************

packages=(
  babel-eslint
  eslint
  eslint-config-airbnb
  eslint-config-flowtype
  eslint-config-prettier
  eslint-config-react-app
  eslint-plugin-prettier
  eslint-plugin-react
  eslint-plugin-import
  eslint-plugin-jsx-a11y
  prettier
  prettier-eslint
)

if [[ -f yarn.lock ]]; then
  for package in ${packages[@]}; do
    yarn add --dev $package
  done
else
  for package in ${packages[@]}; do
    npm install --dev $package
  done
fi

# npx install-peerdeps --dev eslint-config-airbnb

function copy_eslintrc() {
  cat ~/.eslintrc >> .eslintrc
}

if [[ -f .eslintrc ]]; then
  copy_eslintrc
else
  touch .eslintrc && copy_eslintrc
fi

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# prettier-eslint-cli