#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Gems
#
# ****************************************************

gems=(
  bundler
  tmuxinator
)

for gem in ${gems[@]}; do
  gem install $gem
done

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# gem install desktop
# gem install rails
