#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew
#
# ****************************************************

if ! [ -x "$(command -v brew)" ]; then

  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

else

  echo 'Homebrew is already installed on this machine.'

fi