#!/usr/bin/env bash
# ****************************************************
#
#   Homebrew
#
# ****************************************************

if ! [ -x "$(command -v brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo 'Homebrew is already installed on this machine.'
fi