#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Mac App Store Apps
#
# ****************************************************

mas_install() {
  mas list | grep $1 || mas install $1
}

applications=(
  937984704 # Amphetamine
  1290358394 # Cardhop
  924726344 # Deliveries
  975937182 # Fantastical
  990588172 # Gestimer
  1082624744 # Gifox
  1289197285 # MindNode
  803453959 # Slack
  904280696 # Things 3
  1191449274 # ToothFairy
  1384080005 # Tweetbot
  1225570693 # Ulysses
)

for application in ${applications[@]}; do
  mas_install $application
done

# -------------------------------------
#   Disabled
# -------------------------------------

# 427475982 (BreakTime)
# 969418666 (ColorSnapper)
# 1055511498 (Day One)
# 430798174 (HazeOver)
# 603637384 (Name Mangler)
# 928871589 (Noizio)
# 413965349 (Soulver)
# 957734279 (Toggl)
# 1278508951 (Trello)
# 1062679359 (Typeface)
# 1284863847 (Unsplash Wallpapers)
# 1266674560 (Wallpaper Wizard)
# 909760813 (Who's On My WiFi)
# 494803304 (WiFi Explorer)