#!/usr/bin/env bash
# ****************************************************
#
#   NPM
#
# ****************************************************

packages=(
  create-react-app
  gatsby-cli
  npx
  prettier
  prettier-eslint
  prettier-eslint-cli
)

for package in ${packages[@]}; do
  npm install -g $package
done

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# babel-eslint
# eslint
# eslint-config-prettier
# eslint-config-react-app
# eslint-plugin-prettier
# eslint-plugin-react
# eslint-plugin-import
# eslint-plugin-jsx-a11y
# flow-bin
# babel-eslint
# imageoptim-cli
# parker
# psi
# remind
# remind-me
# speed-test
# stylefmt
# stylelint
# stylelint-order
# stylestats
# svgo