#!/usr/bin/env bash
# ****************************************************
#
#   NVM
#
# ****************************************************

function install_latest_node() {
  [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
  nvm install node
  nvm use node
  nvm alias default node
}

if [ ! -d "$HOME/.nvm" ]; then

  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  install_latest_node

else

  echo 'NVM is already installed on this machine. Installing latest Node...'
  install_latest_node

fi
