#!/usr/bin/env bash
# ****************************************************
#
#   Outliers
#   -> Applications not in Cask or the Mac App Store
#
# ****************************************************

# Linear
# https://linear.app/download
