#!/usr/bin/env bash
# ****************************************************
#
#   Outliers
#   -> Applications not in Cask or the Mac App Store
#
# ****************************************************

# Homerow
# https://www.homerow.app/
