#!/usr/bin/env bash
# ****************************************************
#
#   Rbenv
#
# ****************************************************

if [ ! -d "$HOME/.rbenv" ]; then

  echo 'Setting up rbenv...'
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  echo 'Add export PATH="$HOME/.rbenv/bin:$PATH" to your ~/.bash_profile'
  echo 'Add eval "$(rbenv init -)" to your ~/.bash_profile'

  echo 'Setting up ruby-build...'
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

  echo "rbenv is now set up! Type 'rbenv'"

else

  echo 'rbenv is already installed on this machine.'

fi
