#!/usr/bin/env bash
# ****************************************************
#
#   Rbenv
#
# ****************************************************

VERSION='2.5.3'

function install_global_ruby() {
  rbenv install $VERSION
  rbenv rehash
  rbenv global $VERSION
}

if [ ! -d "$HOME/.rbenv" ]; then
  echo 'Setting up rbenv...'
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  echo 'Add export PATH="$HOME/.rbenv/bin:$PATH" to your ~/.bash_profile'
  echo 'Add eval "$(rbenv init -)" to your ~/.bash_profile'

  echo 'Setting up ruby-build...'
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

  echo "rbenv is now set up! Installing latest Ruby..."
  install_global_ruby
else
  echo 'rbenv is already installed on this machine.'

  if [ ! -d "$HOME/.rbenv/versions/$VERSION" ]; then
    install_global_ruby
  else
    echo "Ruby $VERSION is already installed on this machine."
  fi
fi
