#!/usr/bin/env bash
# *************************************
#
#   Terminal Italics
#
# *************************************

tic ~/.dotfiles/iterm/tmux-256color.terminfo
tic ~/.dotfiles/iterm/xterm-256color-italic.terminfo
