#!/usr/bin/env bash
# ****************************************************
#
#   Update
#
# ****************************************************

# Rbenv
cd "$HOME/.rbenv" && git pull && cd -

# Ruby Build
cd "$HOME/.rbenv/plugins/ruby-build" && git pull && cd -

# NVM
(
  cd "$NVM_DIR"
  git fetch --tags origin
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm.sh"

# Git Submodules
git submodule foreach git pull

# Homebrew & Homebrew Packages
brew update && brew cleanup && brew prune && brew doctor