#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew
#
# ****************************************************

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Autojump
# -> A cd command that learns
brew install autojump

# Bash & Bash Completion
brew install bash
brew install bash-completion

# Git
# -> Version control
brew install git

# Hub
# -> Command-line wrapper for git
brew install hub

# MAS
# -> Mac App Store command-line interface
brew install mas

# NVM
# -> Node Version Manager
brew install nvm

# OmniGraffle
brew install omnigraffle

# Postgres
brew install postgres

# Python
brew install python

# reattach-to-user-namespace
# -> Copy/paste to clipboard in tmux
brew install reattach-to-user-namespace

# TheSilverSearcher
# -> A code-searching tool similar to ack, but faster
brew install the_silver_searcher

# tmux
# -> Terminal multiplexer
brew install tmux

# Tree
# -> Recursive directory listing command
brew install tree

# Vim
# -> Ye' old text editor
brew install vim

# Watchman
# -> A file watching service
brew install watchman

# Yarn
# -> Package manager
brew install yarn

# Remove outdated versions from the cellar
brew cleanup

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# Ack
# -> A tool like grep, optimized for programmers
# brew install ack

# Docker
# brew install docker

# Emacs
# brew tap d12frosted/emacs-plus
# brew install emacs-plus
# brew linkapps emacs-plus

# FFmpeg
# -> Record, convert and stream audio and video
# brew install ffmpeg

# GHI
# -> GitHub issues on command line
# brew install ghi

# Gifify
# -> Convert .mov into .gif
# brew install gifify

# Git FTP
# brew install git-ftp

# ImageMagick
# -> Create, edit, compose, or convert bitmap images
# brew install imagemagick

# Neovim
# -> Vim port
# brew install neovim

# Redis
# -> Advanced key-value store
# brew install redis

# Rename
# -> Rename files in the command line
# brew install rename

# Sitespeed.io
# -> Analyze your website speed and performance
# brew install sitespeed.io

# webkit2png
# -> Command-line webpage screenshots
# brew install webkit2png
