#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew
#
# ****************************************************

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Ack
# -> A tool like grep, optimized for programmers
# brew install ack

# Autojump
# -> A cd command that learns
brew install autojump

# Bash & Bash Completion
brew install bash
brew install bash-completion

# FFmpeg
# -> Record, convert and stream audio and video
brew install ffmpeg

# GHI
# -> GitHub issues on command line
brew install ghi

# Git
# -> Version control
brew install git

# Git FTP
brew install git-ftp

# Hub
# -> Command-line wrapper for git
brew install hub

# ImageMagick
# -> Create, edit, compose, or convert bitmap images
brew install imagemagick

# NVM
# -> Node Version Manager
brew install nvm

# reattach-to-user-namespace
# -> Copy/paste to clipboard in tmux
brew install reattach-to-user-namespace

# Redis
# -> Advanced key-value store
brew install redis

# Rename
# -> Rename files in the command line
brew install rename

# Sitespeed.io
# -> Analyze your website speed and performance
brew install sitespeed.io

# TheSilverSearcher
# -> A code-searching tool similar to ack, but faster
brew install the_silver_searcher

# tmux
# -> Terminal multiplexer
brew install tmux

# Tree
# -> Recursive directory listing command
brew install tree

# Vim
# -> Ye' old text editor
brew install vim

# webkit2png
# -> Command-line webpage screenshots
brew install webkit2png

# Remove outdated versions from the cellar
brew cleanup
