#!/usr/bin/env bash

# To list the dependencies
# npm info "eslint-config-airbnb@latest" peerDependencies

(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install -g "$PKG@latest"
)
