#!/usr/bin/env bash

packages=(
  babel-eslint
  eslint
  eslint-config-prettier
  eslint-config-react-app
  eslint-plugin-prettier
  eslint-plugin-react
  eslint-plugin-import
  eslint-plugin-jsx-a11y
  prettier
  prettier-eslint
  prettier-eslint-cli
)

for package in ${packages[@]}; do
  if [[ -f yarn.lock ]]; then
    yarn add --dev $package
  else
    npm install --dev $package
  fi
done

# npx install-peerdeps --dev eslint-config-airbnb

function copy_eslintrc() {
  cat ~/.eslintrc >> .eslintrc
}

if [[ -f .eslintrc ]]; then
  copy_eslintrc
else
  touch .eslintrc && copy_eslintrc
fi