#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Gems
#
# ****************************************************

sudo gem install bundler
sudo gem install coffee-script
sudo gem install desktop
sudo gem install haml
sudo gem install middleman
sudo gem install rails
sudo gem install rdio-cli
sudo gem install sass
sudo gem install sinatra
sudo gem install tmuxinator
