#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Gems
#
# ****************************************************

gem install bundler
gem install rails
gem install tmuxinator

# gem install desktop
