#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew Packages
#
# ****************************************************

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

packages=(
  autojump
  bash
  bash-completion
  git
  hub
  mas
  omnigraffle
  postgres
  python
  reattach-to-user-namespace
  the_silver_searcher
  tmux
  tree
  vim
  watchman
  yarn
)

for package in ${packages[@]}; do
  brew install $package
done

# Remove outdated versions from the cellar
brew cleanup

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# ack
# docker
# ffmpeg
# ghi
# gifify
# git-ftp
# imagemagick
# neovim
# redis
# rename
# sitespeed.io
# webkit2png