#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Mac App Store Apps
#
# ****************************************************

mas_install() {
  mas list | grep $1 || mas install $1
}

# Airmail
# mas_install 918858936

# Boom
# mas_install 948176063

# Bear
mas_install 1091189122

# BreakTime
# mas_install 427475982

# ColorSnapper
mas_install 969418666

mas_install 1055511498

# Deliveries
mas_install 924726344

# Evernote
# mas_install 406056744

# Fantastical
mas_install 975937182

# Gestimer
# mas_install 990588172

# GIPHY Capture
mas_install 668208984

# HazeOver
mas_install 430798174

# iA Writer
# mas_install 775737590

# Monosnap
mas_install 540348655

# Name Mangler
# mas_install 603637384

# NZBVortex
# mas_install 914250185

# Red Hot Timer
# mas_install 929960914

# Slack
mas_install 803453959

# Todoist
mas_install 585829637

# Tweetbot
mas_install 557168941

# Typeface
# mas_install 1062679359

# Who's On My WiFi
# mas_install 909760813
