#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Mac App Store Apps
#
# ****************************************************

mas_install() {
  mas list | grep $1 || mas install $1
}

# Cardhop
mas_install 1290358394

# ColorSnapper
mas_install 969418666

# Deliveries
mas_install 924726344

# Fantastical
mas_install 975937182

# Gestimer
mas_install 990588172

# Gifox
mas_install 1082624744

# HazeOver
mas_install 430798174

# MindNode
mas_install 1289197285

# Slack
mas_install 803453959

# Things 3
mas_install 904280696

# ToothFairy
mas_install 1191449274

# Tweetbot
mas_install 1384080005

# Ulysses
mas_install 1225570693

# Who's On My WiFi
mas_install 909760813

# WiFi Explorer
mas_install 494803304

# -------------------------------------
#   Disabled
# -------------------------------------

# mas_install 427475982 (BreakTime)
# mas_install 1055511498 (Day One)
# mas_install 603637384 (Name Mangler)
# mas_install 928871589 (Noizio)
# mas_install 413965349 (Soulver)
# mas_install 957734279 (Toggl)
# mas_install 1278508951 (Trello)
# mas_install 1062679359 (Typeface)
# mas_install 1284863847 (Unsplash Wallpapers)
# mas_install 1266674560 (Wallpaper Wizard)