#!/usr/bin/env bash
# ****************************************************
#
#   Setup - NPM
#
# ****************************************************

packages=(
  bower
  grunt
  grunt-cli
  gulp
  imageoptim-cli
  jasmine-node
  stylestats
  svgo
  parker
  psi
  yo
)

for package in ${packages[@]}; do
  npm install -g $package
done
