#!/usr/bin/env bash
# ****************************************************
#
#   Setup - NPM
#
# ****************************************************

packages=(
  create-react-app
  eslint
  eslint-config-prettier
  eslint-plugin-prettier
  flow-bin
  npx
  prettier
  prettier-eslint
  prettier-eslint-cli
  # babel-eslint
  # imageoptim-cli
  # parker
  # psi
  # remind
  # remind-me
  # speed-test
  # stylefmt
  # stylelint
  # stylelint-order
  # stylestats
  # svgo
)

for package in ${packages[@]}; do
  npm install -g $package
done
