#!/usr/bin/env bash
# ****************************************************
#
#   Setup - NVM
#
# ****************************************************

if [ ! -d "$HOME/.nvm" ]; then

  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

else

  echo 'NVM is already installed on this machine.'

fi
