#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Outliers
#   -> Applications not in Cask or the Mac App Store
#
# ****************************************************

# ----------------------------------------------------
#   Start
# ----------------------------------------------------

cd ~/Downloads

# ----------------------------------------------------
#   Heroku
# ----------------------------------------------------

echo 'Downloading Heroku Toolbelt...'
open https://toolbelt.heroku.com/
echo 'Downloaded! Run heroku plugins:install https://github.com/heroku/heroku-accounts.git'

# ----------------------------------------------------
#   End
# ----------------------------------------------------

cd -
