#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Outliers
#   -> Applications not in Cask or the Mac App Store
#
# ****************************************************

# ----------------------------------------------------
#   Start
# ----------------------------------------------------

cd ~/Downloads

# ----------------------------------------------------
#   Bartender 2
# ----------------------------------------------------

echo 'Downloading Bartender 2...'
download-zip http://www.macbartender.com/Demo/Bartender%202.zip
echo 'Downloaded!'

# ----------------------------------------------------
#   CleanMyMac 3
# ----------------------------------------------------

echo 'Downloading CleanMyMac 3...'
open http://macpaw.com/download/cleanmymac
echo 'Downloaded!'

# ----------------------------------------------------
#   Heroku
# ----------------------------------------------------

echo 'Downloading Heroku Toolbelt...'
open https://toolbelt.heroku.com/
echo 'Downloaded! Run heroku plugins:install https://github.com/heroku/heroku-accounts.git'

# ----------------------------------------------------
#   Rdio
# ----------------------------------------------------

echo 'Downloading Rdio...'
open http://rdio0-a.akamaihd.net/media/static/desktop/mac/Rdio.dmg
echo 'Downloaded!'

# ----------------------------------------------------
#   End
# ----------------------------------------------------

cd -
