#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Sublime Text
#
# ****************************************************

cd ~/Library/Application\ Support/Sublime\ Text\ 3/
rm -rf Packages
ln -s ~/.dotfiles/sublime-text/Packages Packages
echo 'Symlinked ~/.dotfiles/sublime-text/Packages to Sublime Text Packages'

ln -s ~/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
echo 'Symlinked Sublime Text subl to /usr/local/bin/subl'
